### ISSUE TITLE
Map view has scrollbar that shouldn't be there 

### ISSUE THREAD

**Issue by pierotofy** [DroneDB/Hub#22]
![image](https://user-images.githubusercontent.com/1951843/122828019-1ea46000-d2b3-11eb-88d0-349af26b11c5.png)

Notice the scrollbar on the right. This was probably introduced with the changes in #18. The map should not scroll past the size of the screen and no scrollbars should appear (expect the one in the Explorer component).

**Comment by HeDo88TH** [comment]
I succeeded in reproducing this issue. It happens when the viewport height is less than 700px. I could not identify exactly what is causing it but I suspect it's the map canvas. The scrollbar appears between 700px and 665px (35px). We need to investigate further but I think that it's not high priority, very few devices have screens this small.

**Comment by HeDo88TH** [comment]
Fixed by https://github.com/DroneDB/CommonUI/pull/4
